import { NextResponse } from 'next/server'
import { db } from '@/lib/db'

export const WCM_ACTIVE_PPTS_DATA = [
  // Sumowono
  {
    code: 'RT0000021083',
    name: 'SURYA TANI',
    address: 'Kec. Sumowono',
    district: 'Sumowono',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '11/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 215,
    realisasiUrea: 133,
    sisaUrea: 82,
    alokasiNpk: 210,
    realisasiNpk: 90,
    sisaNpk: 120,
  },
  {
    code: 'RT0000021058',
    name: 'BINA MAJU JAYA',
    address: 'Kec. Sumowono',
    district: 'Sumowono',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '10/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 224,
    realisasiUrea: 158,
    sisaUrea: 66,
    alokasiNpk: 260,
    realisasiNpk: 115,
    sisaNpk: 145,
  },
  {
    code: 'RT0000085298',
    name: 'AGRO LESTARI',
    address: 'Kec. Sumowono',
    district: 'Sumowono',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '09/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 256,
    realisasiUrea: 93,
    sisaUrea: 163,
    alokasiNpk: 350,
    realisasiNpk: 98,
    sisaNpk: 252,
  },
  // Pringapus
  {
    code: 'RT0000088748',
    name: 'MAJU RAHAYU',
    address: 'Kec. Pringapus',
    district: 'Pringapus',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '03/SPJB/AM-PPTS/XII/25-rev',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 210,
    realisasiUrea: 141,
    sisaUrea: 69,
    alokasiNpk: 170,
    realisasiNpk: 145,
    sisaNpk: 25,
  },
  {
    code: 'RT0000021104',
    name: 'ENGGAL SEMI',
    address: 'Kec. Pringapus',
    district: 'Pringapus',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '02/SPJB/AM-PPTS/XII/25.',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 198,
    realisasiUrea: 115,
    sisaUrea: 83,
    alokasiNpk: 165,
    realisasiNpk: 117,
    sisaNpk: 48,
  },
  {
    code: 'RT0000089485',
    name: 'WAHYU LESTARI',
    address: 'Kec. Pringapus',
    district: 'Pringapus',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '08/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 103,
    realisasiUrea: 73.5,
    sisaUrea: 29.5,
    alokasiNpk: 60,
    realisasiNpk: 40,
    sisaNpk: 20,
  },
  {
    code: 'RT0000017846',
    name: 'TOKO MARISA',
    address: 'Kec. Pringapus',
    district: 'Pringapus',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '07/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 490,
    realisasiUrea: 264.5,
    sisaUrea: 225.5,
    alokasiNpk: 350,
    realisasiNpk: 290,
    sisaNpk: 60,
  },
  {
    code: 'RT0000021111',
    name: 'SINGOJOYO',
    address: 'Kec. Pringapus',
    district: 'Pringapus',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '06/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 137,
    realisasiUrea: 58,
    sisaUrea: 79,
    alokasiNpk: 130,
    realisasiNpk: 46,
    sisaNpk: 84,
  },
  {
    code: 'RT0000021109',
    name: 'NGUDI MAKMUR',
    address: 'Kec. Pringapus',
    district: 'Pringapus',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '05/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 330,
    realisasiUrea: 230.5,
    sisaUrea: 99.5,
    alokasiNpk: 275,
    realisasiNpk: 275,
    sisaNpk: 0,
  },
  {
    code: 'RT0000021108',
    name: 'MEKAR',
    address: 'Kec. Pringapus',
    district: 'Pringapus',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '04/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 131,
    realisasiUrea: 67,
    sisaUrea: 64,
    alokasiNpk: 125,
    realisasiNpk: 70,
    sisaNpk: 55,
  },
  {
    code: 'RT0000088746',
    name: 'Bina Tani',
    address: 'Kec. Pringapus',
    district: 'Pringapus',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '01/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 101,
    realisasiUrea: 45,
    sisaUrea: 56,
    alokasiNpk: 70,
    realisasiNpk: 43,
    sisaNpk: 27,
  },
  // Tuntang
  {
    code: 'RT0000094478',
    name: 'KDMP Gedangan',
    address: 'Kec. Tuntang',
    district: 'Tuntang',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '18/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 73,
    realisasiUrea: 24,
    sisaUrea: 49,
    alokasiNpk: 55,
    realisasiNpk: 18,
    sisaNpk: 37,
  },
  {
    code: 'RT0000094477',
    name: 'KDMP Sraten',
    address: 'Kec. Tuntang',
    district: 'Tuntang',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '17/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 52,
    realisasiUrea: 14,
    sisaUrea: 38,
    alokasiNpk: 35,
    realisasiNpk: 13,
    sisaNpk: 22,
  },
  {
    code: 'RT0000021094',
    name: 'USAHA TANI',
    address: 'Kec. Tuntang',
    district: 'Tuntang',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '16/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 205,
    realisasiUrea: 67.5,
    sisaUrea: 137.5,
    alokasiNpk: 155,
    realisasiNpk: 48,
    sisaNpk: 107,
  },
  {
    code: 'RT0000021093',
    name: 'UMEGA',
    address: 'Kec. Tuntang',
    district: 'Tuntang',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '15/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 105,
    realisasiUrea: 47,
    sisaUrea: 58,
    alokasiNpk: 75,
    realisasiNpk: 41,
    sisaNpk: 34,
  },
  {
    code: 'RT0000021079',
    name: 'SUKAMAJU',
    address: 'Kec. Tuntang',
    district: 'Tuntang',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '14/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 78,
    realisasiUrea: 50,
    sisaUrea: 28,
    alokasiNpk: 60,
    realisasiNpk: 24,
    sisaNpk: 36,
  },
  {
    code: 'RT0000021064',
    name: 'KUD BINA DHARMA',
    address: 'Kec. Tuntang',
    district: 'Tuntang',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '13/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 83,
    realisasiUrea: 35,
    sisaUrea: 48,
    alokasiNpk: 60,
    realisasiNpk: 26,
    sisaNpk: 34,
  },
  {
    code: 'RT0000091576',
    name: 'DAYA AKSARA',
    address: 'Kec. Tuntang',
    district: 'Tuntang',
    regency: 'Kab. Semarang',
    province: 'Jawa Tengah',
    spjbNumber: '12/SPJB/AM-PPTS/XII/25',
    spjbDate: '01-12-2025',
    spjbValidFrom: '01-01-2026',
    spjbValidUntil: '31-12-2026',
    alokasiUrea: 90,
    realisasiUrea: 28.5,
    sisaUrea: 61.5,
    alokasiNpk: 70,
    realisasiNpk: 16.5,
    sisaNpk: 53.5,
  },
]

export async function GET() {
  return POST()
}

export async function POST() {
  try {
    const results: unknown[] = []
    for (const item of WCM_ACTIVE_PPTS_DATA) {
      const ppts = await db.ppts.upsert({
        where: { code: item.code },
        update: {
          name: item.name,
          address: item.address,
          district: item.district,
          regency: item.regency,
          province: item.province,
          spjbNumber: item.spjbNumber,
          spjbDate: item.spjbDate,
          spjbValidFrom: item.spjbValidFrom,
          spjbValidUntil: item.spjbValidUntil,
          alokasiUrea: item.alokasiUrea,
          realisasiUrea: item.realisasiUrea,
          sisaUrea: item.sisaUrea,
          alokasiNpk: item.alokasiNpk,
          realisasiNpk: item.realisasiNpk,
          sisaNpk: item.sisaNpk,
          isActive: true,
        },
        create: {
          code: item.code,
          name: item.name,
          address: item.address,
          district: item.district,
          regency: item.regency,
          province: item.province,
          spjbNumber: item.spjbNumber,
          spjbDate: item.spjbDate,
          spjbValidFrom: item.spjbValidFrom,
          spjbValidUntil: item.spjbValidUntil,
          alokasiUrea: item.alokasiUrea,
          realisasiUrea: item.realisasiUrea,
          sisaUrea: item.sisaUrea,
          alokasiNpk: item.alokasiNpk,
          realisasiNpk: item.realisasiNpk,
          sisaNpk: item.sisaNpk,
          isActive: true,
        },
      })
      results.push(ppts)
    }

    return NextResponse.json({
      message: `Berhasil meng-update & memasukkan ${results.length} data SPJB PPTS dari WCM ke database`,
      count: results.length,
      data: results,
    })
  } catch (error) {
    console.error('Error seeding PPTS WCM data:', error)
    return NextResponse.json({ error: 'Gagal memasukkan data WCM ke database' }, { status: 500 })
  }
}
